// User Auth
export const AUTH = "AUTH";
export const LOGOUT = "LOGOUT";

// COMMON
export const ALL_LOADING = "ALL_LOADING";
export const ALL_ALERT = "ALL_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

// Appointment
export const FETCH_ALL_APPOINTMENTS = "FETCH_ALL_APPOINTMENTS";
export const FETCH_APPOINTMENT_BY_ID = "FETCH_APPOINTMENT_BY_ID";
export const CREATE_APPOINTMENT = "CREATE_APPOINTMENT";
export const UPDATE_APPOINTMENT = "UPDATE_APPOINTMENT";
export const DELETE_APPOINTMENT = "DELETE_APPOINTMENT";

// Article
export const FETCH_ALL_ARTICLES = "FETCH_ALL_ARTICLES";
export const FETCH_ARTICLE_BY_ID = "FETCH_ARTICLE_BY_ID";
export const CREATE_ARTICLE = "CREATE_ARTICLE";
export const UPDATE_ARTICLE = "UPDATE_ARTICLE";
export const DELETE_ARTICLE = "DELETE_ARTICLE";

// Inventory
export const FETCH_ALL_INVENTORIES = "FETCH_ALL_INVENTORIES";
export const FETCH_INVENTORY_BY_ID = "FETCH_INVENTORY_BY_ID";
export const CREATE_INVENTORY = "CREATE_INVENTORY";
export const UPDATE_INVENTORY = "UPDATE_INVENTORY";
export const DELETE_INVENTORY = "DELETE_INVENTORY";

// Pet
export const FETCH_ALL_PETS = "FETCH_ALL_PETS";
export const FETCH_PET_BY_ID = "FETCH_PET_BY_ID";
export const CREATE_PET = "CREATE_PET";
export const UPDATE_PET = "UPDATE_PET";
export const DELETE_PET = "DELETE_PET";

// Prescription
export const FETCH_ALL_PRESCRIPTIONS = "FETCH_ALL_PRESCRIPTIONS";
export const FETCH_PRESCRIPTION_BY_ID = "FETCH_PRESCRIPTION_BY_ID";
export const CREATE_PRESCRIPTION = "CREATE_PRESCRIPTION";
export const UPDATE_PRESCRIPTION = "UPDATE_PRESCRIPTION";
export const DELETE_PRESCRIPTION = "DELETE_PRESCRIPTION";

// Transport
export const FETCH_ALL_TRANSPORTS = "FETCH_ALL_TRANSPORTS";
export const FETCH_TRANSPORT_BY_ID = "FETCH_TRANSPORT_BY_ID";
export const CREATE_TRANSPORT = "CREATE_TRANSPORT";
export const UPDATE_TRANSPORT = "UPDATE_TRANSPORT";
export const DELETE_TRANSPORT = "DELETE_TRANSPORT";

// User
export const FETCH_ALL_USERS = "FETCH_ALL_USERS";
export const CREATE_USER = "CREATE_USER";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";

// Vet
export const FETCH_ALL_VETS = "FETCH_ALL_VETS";
export const FETCH_VET_BY_ID = "FETCH_VET_BY_ID";
export const CREATE_VET = "CREATE_VET";
export const UPDATE_VET = "UPDATE_VET";
export const DELETE_VET = "DELETE_VET";
